### PR TITLE
dependency-fix

### PR DESCRIPTION
**Pull request by knotenpunkt**
see title

### CODE REVIEW

**Comment by knotenpunkt** [comment]
@fischerbenjamin can you take a look, if this is correct, what i do there,.... i want to merge back the change by the dependency bot. It says 1 file and 1 line changed. But what does the 4 commits in the list mean?

**Comment by fischerbenjamin** [comment]
I think these are the merge commits in master and since you merge from master into develop again and they are not present, they will be merged back

**Comment by knotenpunkt** [comment]
hm ok, so you think i can merge it?

**Comment by fischerbenjamin** [comment]
I think so, it definetly won't break anything :)

**Comment by knotenpunkt** [comment]
its done^^

**Pull request merged**
